### PR TITLE
explorer: fix navigation bug on detail pages

### LINKED ISSUE #1771: explorer: fix navigation bug on block details page
#### Summary
While on the block details page if the user tries to navigate through the block height with the available arrows the data on the page will not update to the corresponding block height even though the url will change to the corresponding block hash.

### PR DESCRIPTION
**Pull request by deuch13**
Resolves #1771

### CODE REVIEW

**Review by nortonandreev — APPROVED** [review]

**Review by nortonandreev — CHANGES_REQUESTED** [review]
You will need to change the behavior of the back button on the block details.

**Comment by nortonandreev** [comment]
https://github.com/dusk-network/rusk/assets/34094428/18a06ca2-4fd2-4b37-9dfa-901db308ba92

I think the back should either navigate the user back to the home page or the blocks page – depending on what the referrer was.

Currently it seems it's just the browser's back, which if not ideal, if the user has navigated to another block from the block details page.

**Comment by nortonandreev** [comment]
Not sure if as part of this PR, or additionally, but it will be good to add a check on the "next" button so that it is disabled, if a higher block doesn't exist.

Otherwise the user will see this, currently not very informative error.

https://github.com/dusk-network/rusk/assets/34094428/5d9dc14d-fe8a-4e91-98ff-a2a5ce8fb993

**Comment by deuch13** [comment]
> Not sure if as part of this PR, or additionally, but it will be good to add a check on the "next" button so that it is disabled, if a higher block doesn't exist.
> 
> Otherwise the user will see this, currently not very informative error.
> 
>  Screen.Recording.2024-05-22.at.13.16.52.mov

Disable it or hide it completely?

**Comment by nortonandreev** [comment]
> > Not sure if as part of this PR, or additionally, but it will be good to add a check on the "next" button so that it is disabled, if a higher block doesn't exist.
> > Otherwise the user will see this, currently not very informative error.
> > Screen.Recording.2024-05-22.at.13.16.52.mov
> 
> Disable it or hide it completely?

Yeah, this is also fine!

**Comment by kieranhall** [comment]
> > Not sure if as part of this PR, or additionally, but it will be good to add a check on the "next" button so that it is disabled, if a higher block doesn't exist.
> > Otherwise the user will see this, currently not very informative error.
> > Screen.Recording.2024-05-22.at.13.16.52.mov
> 
> Disable it or hide it completely?

I think disabling is better.  This would probably be better as a separate issue and to check with @laremas that this is the way to go etc.

**Comment by laremas** [comment]
Yeah, I agree with @kieranhall would be better to disable it in case an higher block does not exist

**Review by ascartabelli — APPROVED** [review]

**Review by nortonandreev — APPROVED** [review]

**Pull request merged**
