### PR TITLE
explorer: Tweak media queries for home page tables

### LINKED ISSUE #1887: Tweak media queries for home page tables
#### Summary
The blocks and transactions table in the home page tend to go one below the other even with fairly large resolutions.
By tweaking the media queries, ~and making the gas column disappear on some breakpoints,~ we can achieve more tolerance to have them side by side.

(edit: we decided to avoid showing the gas column altogether)

### PR DESCRIPTION
**Pull request by ascartabelli**
Resolves #1887

### CODE REVIEW

**Comment by nortonandreev** [comment]
I do agree that the breakpoint to display both tables side-by-side is quite large. I'm personally not a huge fan of showing different info based on the viewport, however, if the gas is not that important, it could be okay.

**Review by nortonandreev — DISMISSED** [review]

**Comment by ascartabelli** [comment]
> I do agree that the breakpoint to display both tables side-by-side is quite large. I'm personally not a huge fan of showing different info based on the viewport, however, if the gas is not that important, it could be okay.

My reasoning was that the tables in home page are meant to give a quick summary, so I sacrificed what seemed to be the least important column.
I'll run this by the others in the standup anyway before merging.

**Comment by kieranhall** [comment]
If we can avoid hiding information with media queries, that would be ideal and  I would like to explorer the options here.

CC @laremas

**Comment by ascartabelli** [comment]
> If we can avoid hiding information with media queries, that would be ideal and I would like to explorer the options here.
> 
> CC @laremas

We are not doing that, actually.

**Review by deuch13 — APPROVED** [review]
LGTM!

**Pull request merged**
