### PR TITLE
Add `iteration` to block header

### LINKED ISSUE #848: node: Add Iteration field to Block header
Describe the bug
This is needed in order to reflect protocol changes made in https://github.com/dusk-network/dusk-blockchain/issues/1500

### PR DESCRIPTION
**Pull request by herr-seppia**
- Add `iteration` to block header
- Remove `step` from header's certificate

Ps: This is needed in order to reflect protocol changes made in dusk-network/dusk-blockchain#1500

Resolves #848

### CODE REVIEW

**Review by fed-franz — APPROVED** [review]
LGTM

It wouldn't hurt to add a bit of explanation in the PR description.

**Comment by herr-seppia** [comment]
@fed-franz added

Description was a couple of link away 😉

**Review by HDauven — APPROVED** [review]

**Comment by fed-franz** [comment]
> Description was a couple of link away wink

I know, but it doesn't look quite clear to me, since the linked PR is to include `step`to the certificate,
while here we're removing it (in favor of adding the iteration to the header).

**Comment by herr-seppia** [comment]
First approach was to simply move the `step` from the certificate to the header (this way the step/iteration was part of the hashed fields), to fix a potential malleability issue.

While implementing the dusk-blockchain PR, we figure out 2 issues/concerns:
1) Step at selection was different than the one in the reduction (ofc, but they still refer to the same iteration)
2) having the step in the certificate was always filled with multiple of 3 (here again, ofc)

So, we decided to move the step from the block completely in favor of `iteration`, since the two are redundant infos and `iteration` is more clear.

Ps: we remove the step only from the block, and not from the reduction messages all over the wire (step is still important there)

**Pull request merged**
