### PR TITLE
web-wallet: Fix Transactions component whitespaces

### LINKED ISSUE #2101: web-wallet: Missing whitespace for the empty state (Transactions list)
Screenshot 2024-08-10 at 18 31 03

### PR DESCRIPTION
**Pull request by nortonandreev**
Resolves #2101

### CODE REVIEW

**Comment by nortonandreev** [comment]
**Note:** I have used [this](https://www.figma.com/design/z6UnA0BtMBUKIcCXD975um/Wallet-Extension-(JULY-26th)?node-id=6207-159535&t=HniMuMVDWLaY2Rd6-4) artboard as a reference for the padding.

**Review by kieranhall — APPROVED** [review]
LGTM

**Review by ascartabelli — CHANGES_REQUESTED** [review]
You forgot a changelog entry for this.

**Comment by nortonandreev** [comment]
> You forgot a changelog entry for this.

This was a regression caused by https://github.com/dusk-network/rusk/issues/1922. I omitted it from the changelog, as the change did not get released to the public.

**Comment by ascartabelli** [comment]
> > You forgot a changelog entry for this.
> 
> This was a regression caused by #1922. I omitted it from the changelog, as the change did not get released to the public.

Ok, then.

**Review by ascartabelli — APPROVED** [review]

**Pull request merged**
