### PR TITLE
rusk-wallet: Add moonlight support

### LINKED ISSUE #2288: rusk-wallet: Add support to create moonlight transactions
#### Summary
Add support to create moonlight transactions.

### PR DESCRIPTION
**Pull request by moCello**
This PR adds basic support of moonlight transactions.
In further issues we will also want to add specific methods to create moonlight-stake, moonlight-unstake and moonlight-stake-withdrawal transactions.

Resolves #2288

### CODE REVIEW

**Review by Daksh14 — DISMISSED** [review]
LGTM. The stake unstake functions are there for testing across rusk not exposed yet via rusk wallet

**Review by ZER0 — CHANGES_REQUESTED** [review]
Before I proceed with the review, I'd like to provide some general feedback. Please note that my review will focus solely on the `wallet-core` section. I will ensure it is properly structured for both FFI/WASM and native support. As for the other areas, I will leave those to your discretion.

1. **Remove `#![allow(clippy::module_name_repetitions)]`:** If you are encountering Clippy warnings about module name repetitions, it suggests that the module, type, or function names are not appropriately chosen. The attribute is there for a reason, and removing it may help identify where naming improvements are needed.

2. **Avoid having a `phoenix` module:** We already have a `notes` module, and since I’ve moved `phoenix_balance` there, we can consolidate. The `notes` module can serve as a "discriminant," meaning we can have one model using `notes` and another using `account`. Ensure that everything related to "notes" is handled within the `notes` namespace/module, and we can then decide how best to integrate moonlight from there.

I will proceed with the review of the `wallet-core` section once the aforementioned points are addressed.

Please @moCello  note that any changes to `wallet-core` are currently blocking my work on FFI and w3sper. As my changes need to be built on top of yours, it’s crucial that your revisions are handled properly and promptly.

**Review by ZER0 — DISMISSED** [review]
LGTM

**Review by ureeves — APPROVED** [review]
:raised_hands:

**Pull request merged**
