### PR TITLE
Add performance benchmarks for AST

### PR DESCRIPTION
**Pull request by ureeves**
Introduces benchmarks for evaluating state transition acceptance, providing a reliable metric for measuring performance under optimal conditions. The objective is to determine a definitive upper limit, considering both virtual machine performance and proof verification overhead. The benchmarks encompass a range of transaction counts per block.

Here's the results (time in **ms**):

| TXs in Block |  Fastest |  Average |  Slowest |
|------------:|---------:|---------:|---------:|
|     1        |  39.092  |  39.257  |  39.426  |
|     2        |  55.347  |  55.485  |  55.624  |
|     3        |  71.786  |  73.190  |  75.195  |
|     4        |  85.570  |  85.785  |  85.996  |
|     5        |  103.93  |  106.34  |  109.32  |
|     10       |  183.85  |  187.01  |  191.32  |
|     20       |  339.02  |  342.64  |  349.07  |
|     30       |  498.44  |  499.34  |  500.24  |
|     40       |  658.35  |  661.98  |  668.44  |
|     50       |  818.41  |  822.85  |  828.68  |
|     60       |  979.92  |  981.74  |  983.76  |
|     70       |  1133.4  |  1135.0  |  1136.7  |
|     80       |  1289.3  |  1290.7  |  1292.0  |
|     90       |  1450.7  |  1461.0  |  1475.1  |
|     100      |  1609.6  |  1611.9  |  1614.3  |

Benchmarks were ran on a `AMD Ryzen 9 5950X`, using around 3 cores at 100% during the run, and a memory usage profile of around 64MiB.

Resolves: #361

### CODE REVIEW

**Review by fed-franz — APPROVED** [review]
Nice!

**Comment by herr-seppia** [comment]
On `Apple M1 Pro`
| TXs in Block |  Fastest |  Average |  Slowest |
|------------:|---------:|---------:|---------:|
| 1 | 26.918 | 27.017 | 27.123 | 
| 2 | 39.932 | 40.098 | 40.277 | 
| 3 | 52.835 | 52.972 | 53.122 | 
| 4 | 65.497 | 65.795 | 66.140 | 
| 5 | 78.384 | 78.611 | 78.866 | 
| 10 | 143.74 | 144.48 | 145.57 | 
| 20 | 274.75 | 276.31 | 278.41 | 
| 30 | 408.08 | 409.52 | 411.26 | 
| 40 | 549.65 | 551.93 | 554.50 | 
| 50 | 678.02 | 681.48 | 685.35 | 
| 60 | 806.20 | 810.20 | 814.74 | 
| 70 | 933.25 | 936.90 | 940.89 | 
| 80 | 1069.6 | 1074.6 | 1080.0 |
| 90 | 1189.7 | 1193.3 | 1197.3 |
| 100 | 1321.4 | 1328.8 | 1337.8 |

**Review by herr-seppia — APPROVED** [review]
LGTM

**Comment by HDauven** [comment]
DO Droplet Premium AMD 1 vCPU 2GB RAM SFO3:
| TXs in Block |  Fastest (ms) |  Average (ms) |  Slowest (ms) |
|--------------|---------------|---------------|---------------|
| 1            | 60.258        | 61.712        | 63.219        |
| 2            | 91.505        | 93.331        | 95.250        |
| 3            | 127.17        | 129.58        | 132.16        |
| 4            | 161.45        | 163.71        | 166.13        |
| 5            | 193.07        | 196.18        | 199.57        |
| 10           | 366.71        | 374.03        | 381.81        |
| 20           | 713.11        | 724.81        | 737.19        |
| 30           | 1088.1        | 1110.2        | 1133.8        |
| 40           | 1429.7        | 1453.5        | 1478.8        |
| 50           | 1740.8        | 1765.4        | 1791.1        |
| 60           | 2099.6        | 2132.7        | 2167.2        |
| 70           | 2395.7        | 2432.2        | 2471.0        |
| 80           | 2744.5        | 2785.6        | 2829.6        |
| 90           | 3232.4        | 3277.9        | 3325.6        |
| 100         | 3479.5        | 3530.7        | 3584.8        |

DO Droplet CPU-optimized regular Intel 2 CPUs 4 GB RAM SFO3:
| TXs in Block |  Fastest (ms) |  Average (ms) |  Slowest (ms) |
|--------------|---------------|---------------|---------------|
| 1            | 43.886        | 44.034        | 44.194        |
| 2            | 71.919        | 72.159        | 72.415        |
| 3            | 99.504        | 99.769        | 100.04        |
| 4            | 126.57        | 126.94        | 127.32        |
| 5            | 153.74        | 154.05        | 154.36        |
| 10           | 292.10        | 292.60        | 293.13        |
| 20           | 569.76        | 570.54        | 571.32        |
| 30           | 844.35        | 845.64        | 847.17        |
| 40           | 1108.9        | 1110.9        | 1113.0        |
| 50           | 1394.4        | 1396.2        | 1398.0        |
| 60           | 1678.3        | 1680.4        | 1682.4        |
| 70           | 1956.3        | 1958.7        | 1961.1        |
| 80           | 2218.7        | 2226.0        | 2238.2        |
| 90           | 2519.9        | 2540.1        | 2569.1        |
| 100          | 2798.2        | 2802.4        | 2806.6        |

**Comment by HDauven** [comment]
On my laptop, an AMD Ryzen 7 5800H:

| TXs in Block |  Fastest (ms) |  Average (ms) |  Slowest (ms) |
|--------------|---------------|---------------|---------------|
| 1            | 24.398        | 24.555        | 24.744        |
| 2            | 38.655        | 38.766        | 38.875        |
| 3            | 53.041        | 53.218        | 53.409        |
| 4            | 66.739        | 66.914        | 67.103        |
| 5            | 82.620        | 83.005        | 83.417        |
| 10           | 153.76        | 154.07        | 154.40        |
| 20           | 295.16        | 295.62        | 296.15        |
| 30           | 437.54        | 437.99        | 438.47        |
| 40           | 580.56        | 581.14        | 581.74        |
| 50           | 722.26        | 722.86        | 723.48        |
| 60           | 865.37        | 866.08        | 866.80        |
| 70           | 1008.0        | 1008.8        | 1009.6        |
| 80           | 1148.7        | 1149.5        | 1150.2        |
| 90           | 1290.9        | 1291.7        | 1292.6        |
| 100          | 1432.9        | 1433.9        | 1434.9        |

**Comment by HDauven** [comment]
On a Raspberry Pi 5 @ 3 GHz:
| TXs in Block | Min Time (ms) | Median Time (ms) | Max Time (ms) |
|-----------|---------------|------------------|---------------|
| 1            | 63.533       | 63.599          | 63.692       |
| 2            | 105.81       | 105.95          | 106.11       |
| 3            | 147.86       | 147.96          | 148.08       |
| 4            | 189.15       | 189.27          | 189.43       |
| 5            | 232.28       | 232.39          | 232.51       |
| 10          | 444.95       | 445.13          | 445.33       |
| 20          | 866.66       | 866.95          | 867.25       |
| 30          | 1290.8       | 1291.3          | 1291.8       |
| 40          | 1714.3       | 1714.9          | 1715.4       |
| 50          | 2137.5       | 2138.2          | 2138.9       |
| 60          | 2569.9       | 2573.3          | 2577.2       |
| 70          | 2991.3       | 2992.2          | 2993.0       |
| 80          | 3413.2       | 3414.2          | 3415.2       |
| 90          | 3839.7       | 3840.6          | 3841.6       |
| 100        | 4267.7       | 4268.6          | 4269.6       |

**Pull request merged**
