### PR TITLE
web-wallet: Fix typos

### PR DESCRIPTION
**Pull request by omahs**
Resolves https://github.com/dusk-network/rusk/issues/1511

### CODE REVIEW

**Comment by nortonandreev** [comment]
When resolving the conflict with the CHANGELOG, you will also need to move the new entry under the `## [Unreleased]` section instead, as the fix will make it into the new release of the component.

Currently, the fix is listed under version 0.2.0 which was already released.

**Comment by nortonandreev** [comment]
Hey @omahs – we won't need the changelog entry, as the fix is not user-facing.

Could you please make sure the Changelog's content is the same as it is on master? I will then approve the PR. 

Apologies.

**Comment by omahs** [comment]
@nortonandreev Hey, no worries, I just copied it from master

**Comment by omahs** [comment]
@nortonandreev I don't have write access to the repo, could you merge?

**Pull request merged**
